include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore # Inspired by https://github.com/rrousselGit/freezed/issues/488
    todo: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false # we sort pub deps by feature not alphabetically
    avoid_positional_boolean_parameters: false # we do use it
