name: perek_main
description: Vprok

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  # Network
  dio: ^4.0.1
  fresh: ^0.4.0
  fresh_dio: ^0.3.1
  pretty_dio_logger: ^1.2.0-beta-1

  # Database
  shared_preferences: ^2.0.8

  # UI
  flutter_svg: ^0.23.0+1
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.1.0

  # Utils
  device_info: ^2.0.3
  package_info: ^2.0.2
  uuid: ^3.0.5
  path_provider: ^2.0.6
  freezed_annotation: ^1.1.0
  enum_to_string: ^2.0.1
  either_dart: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter packages pub run build_runner watch
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^1.1.0

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
